program: train_2.py
method: bayes
metric:
    goal: minimize
    name: val_loss
parameters:
    batch-size:
        values: [2, 4]
    num-epochs:
        value: 10
    lr:
        values: [0.0001, 0.00003, 0.00001]
    report-interval:
        value: 100
    net-name:
        value: 'nafnet_sweep'
    data-path-train:
        value: "/mnt/c/Users/js1044k/Downloads/Data/train/"
    data-path-val:
        value: "/mnt/c/Users/js1044k/Downloads/Data/val"
    prev-net-name:
        value: "test_Varnet"
    optimizer:
        values: ["adam", "adamw", "radam"]
    lr-scheduler-on:
        value: true
    lr-scheduler:
        values: ["cosine", "plateau"]
    loss:
        values: ["mixed", "focal", "index_based", "ssim"]
    cascade:
        value: 6
    chans:
        value: 15
    sens_chans:
        value: 4
    grad-clip-on:
        value: true
    iters-to-grad-acc:
        values: [1, 2, 4, 8]
    wandb-on:
        value: true

command:
    - python3.8
    - ${program}
    - ${args_no_boolean_flags}